export const currenciesList = [
  {
    ticker: 'btc',
    name: 'Bitcoin',
    image: 'https://changenow.io/images/coins/btc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'eth',
    name: 'Ethereum',
    image: 'https://changenow.io/images/coins/eth.svg',
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'xrp',
    name: 'Ripple',
    image: 'https://changenow.io/images/coins/xrp.svg',
    hasExternalId: true,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'usdt',
    name: 'Tether (OMNI)',
    image: 'https://changenow.io/images/coins/usdt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
  },
  {
    ticker: 'usdterc20',
    name: 'Tether (ERC-20)',
    image: 'https://changenow.io/images/coins/usdterc20.svg',
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: true,
    supportsFixedRate: true,
  },
  {
    ticker: 'bch',
    name: 'Bitcoin Cash',
    image: 'https://changenow.io/images/coins/bch.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'bsv',
    name: 'Bitcoin SV',
    image: 'https://changenow.io/images/coins/bsv.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ltc',
    name: 'Litecoin',
    image: 'https://changenow.io/images/coins/ltc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'bnb',
    name: 'Binance Coin (ERC20)',
    image: 'https://changenow.io/images/coins/bnb.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'bnbmainnet',
    name: 'Binance Coin Mainnet',
    image: 'https://changenow.io/images/coins/bnbmainnet.svg',
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'eos',
    name: 'EOS',
    image: 'https://changenow.io/images/coins/eos.svg',
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'xtz',
    name: 'Tezos',
    image: 'https://changenow.io/images/coins/xtz.svg',
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'xlm',
    name: 'Stellar',
    image: 'https://changenow.io/images/coins/xlm.svg',
    hasExternalId: true,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'link',
    name: 'Chainlink',
    image: 'https://changenow.io/images/coins/link.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ada',
    name: 'Cardano',
    image: 'https://changenow.io/images/coins/ada.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'xmr',
    name: 'Monero',
    image: 'https://changenow.io/images/coins/xmr.svg',
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'trx',
    name: 'TRON',
    image: 'https://changenow.io/images/coins/trx.svg',
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'cro',
    name: 'Crypto.Com',
    image: 'https://changenow.io/images/coins/cro.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ht',
    name: 'Huobi Token',
    image: 'https://changenow.io/images/coins/ht.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'dash',
    name: 'Dash',
    image: 'https://changenow.io/images/coins/dash.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'etc',
    name: 'Ethereum Classic',
    image: 'https://changenow.io/images/coins/etc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: true,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'usdc',
    name: 'USD Coin',
    image: 'https://changenow.io/images/coins/usdc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
  },
  {
    ticker: 'neo',
    name: 'Neo',
    image: 'https://changenow.io/images/coins/neo.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'atom',
    name: 'Cosmos',
    image: 'https://changenow.io/images/coins/atom.svg',
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'iota',
    name: 'IOTA',
    image: 'https://changenow.io/images/coins/iota.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'zec',
    name: 'Zcash',
    image: 'https://changenow.io/images/coins/zec.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'xem',
    name: 'NEM',
    image: 'https://changenow.io/images/coins/xem.svg',
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ont',
    name: 'Ontology',
    image: 'https://changenow.io/images/coins/ont.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'doge',
    name: 'Dogecoin',
    image: 'https://changenow.io/images/coins/doge.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'bat',
    name: 'Basic Attention Token',
    image: 'https://changenow.io/images/coins/bat.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'vet',
    name: 'VeChain',
    image: 'https://changenow.io/images/coins/vet.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'pax',
    name: 'Paxos Standard Token',
    image: 'https://changenow.io/images/coins/pax.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
  },
  {
    ticker: 'dgb',
    name: 'DigiByte',
    image: 'https://changenow.io/images/coins/dgb.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'busd',
    name: 'Binance USD  (ERC-20)',
    image: 'https://changenow.io/images/coins/busd.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: false,
  },
  {
    ticker: 'btg',
    name: 'Bitcoin Gold',
    image: 'https://changenow.io/images/coins/btg.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'lsk',
    name: 'Lisk',
    image: 'https://changenow.io/images/coins/lsk.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'icx',
    name: 'ICON',
    image: 'https://changenow.io/images/coins/icx.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'dcr',
    name: 'Decred',
    image: 'https://changenow.io/images/coins/dcr.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'qtum',
    name: 'QTUM',
    image: 'https://changenow.io/images/coins/qtum.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'hbar',
    name: 'Hedera Hashgraph',
    image: 'https://changenow.io/images/coins/hbar.svg',
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'tusd',
    name: 'TrueUSD',
    image: 'https://changenow.io/images/coins/tusd.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: true,
  },
  {
    ticker: 'zrx',
    name: '0x',
    image: 'https://changenow.io/images/coins/zrx.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'knc',
    name: 'Kyber Network',
    image: 'https://changenow.io/images/coins/knc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'rvn',
    name: 'Ravencoin',
    image: 'https://changenow.io/images/coins/rvn.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'rep',
    name: 'Augur',
    image: 'https://changenow.io/images/coins/rep.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'enj',
    name: 'Enjin Coin',
    image: 'https://changenow.io/images/coins/enj.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'waves',
    name: 'Waves',
    image: 'https://changenow.io/images/coins/waves.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'bcd',
    name: 'Bitcoin Diamond',
    image: 'https://changenow.io/images/coins/bcd.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'omg',
    name: 'OmiseGo',
    image: 'https://changenow.io/images/coins/omg.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'dai',
    name: 'Dai',
    image: 'https://changenow.io/images/coins/dai.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: false,
  },
  {
    ticker: 'sc',
    name: 'Siacoin',
    image: 'https://changenow.io/images/coins/sc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'mco',
    name: 'Crypto.Com',
    image: 'https://changenow.io/images/coins/mco.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'nano',
    name: 'Nano',
    image: 'https://changenow.io/images/coins/nano.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'dgd',
    name: 'DigixDAO',
    image: 'https://changenow.io/images/coins/dgd.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'snt',
    name: 'Status',
    image: 'https://changenow.io/images/coins/snt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'steem',
    name: 'Steem',
    image: 'https://changenow.io/images/coins/steem.svg',
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'kmd',
    name: 'Komodo',
    image: 'https://changenow.io/images/coins/kmd.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'nexo',
    name: 'Nexo',
    image: 'https://changenow.io/images/coins/nexo.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ren',
    name: 'Ren',
    image: 'https://changenow.io/images/coins/ren.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'hot',
    name: 'Holo',
    image: 'https://changenow.io/images/coins/hot.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'zil',
    name: 'Zilliqa',
    image: 'https://changenow.io/images/coins/zil.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'btt',
    name: 'BitTorrent',
    image: 'https://changenow.io/images/coins/btt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'matic',
    name: 'Matic',
    image: 'https://changenow.io/images/coins/matic.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'lend',
    name: 'Aave',
    image: 'https://changenow.io/images/coins/lend.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'zen',
    name: 'Horizen',
    image: 'https://changenow.io/images/coins/zen.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'hc',
    name: 'HyperCash',
    image: 'https://changenow.io/images/coins/hc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'xvg',
    name: 'Verge',
    image: 'https://changenow.io/images/coins/xvg.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'iost',
    name: 'Internet of Services',
    image: 'https://changenow.io/images/coins/iost.svg',
    hasExternalId: true,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'mana',
    name: 'Decentraland',
    image: 'https://changenow.io/images/coins/mana.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'gnt',
    name: 'Golem',
    image: 'https://changenow.io/images/coins/gnt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'xzc',
    name: 'Zcoin',
    image: 'https://changenow.io/images/coins/xzc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'elf',
    name: 'aelf',
    image: 'https://changenow.io/images/coins/elf.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ardr',
    name: 'Ardor',
    image: 'https://changenow.io/images/coins/ardr.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'rcn',
    name: 'Ripio Credit Network',
    image: 'https://changenow.io/images/coins/rcn.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'lrc',
    name: 'Loopring',
    image: 'https://changenow.io/images/coins/lrc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ae',
    name: 'Aeternity',
    image: 'https://changenow.io/images/coins/ae.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'aion',
    name: 'Aion',
    image: 'https://changenow.io/images/coins/aion.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'strat',
    name: 'Stratis',
    image: 'https://changenow.io/images/coins/strat.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'rlc',
    name: 'iExec',
    image: 'https://changenow.io/images/coins/rlc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'powr',
    name: 'Power Ledger',
    image: 'https://changenow.io/images/coins/powr.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'npxs',
    name: 'Pundi X',
    image: 'https://changenow.io/images/coins/npxs.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ark',
    name: 'Ark',
    image: 'https://changenow.io/images/coins/ark.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'band',
    name: 'Band Protocol',
    image: 'https://changenow.io/images/coins/band.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'tnt',
    name: 'Tierion',
    image: 'https://changenow.io/images/coins/tnt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'eur',
    name: 'Euro',
    image: 'https://changenow.io/images/coins/eur.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'beam',
    name: 'BEAM',
    image: 'https://changenow.io/images/coins/beam.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'wtc',
    name: 'Waltonchain',
    image: 'https://changenow.io/images/coins/wtc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'mtl',
    name: 'Metal',
    image: 'https://changenow.io/images/coins/mtl.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'pivx',
    name: 'PIVX',
    image: 'https://changenow.io/images/coins/pivx.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'loom',
    name: 'Loom Network',
    image: 'https://changenow.io/images/coins/loom.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'fet',
    name: 'Fetch',
    image: 'https://changenow.io/images/coins/fet.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'bnt',
    name: 'BancorNetworkToken',
    image: 'https://changenow.io/images/coins/bnt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'storj',
    name: 'Storj',
    image: 'https://changenow.io/images/coins/storj.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'cvc',
    name: 'Civic',
    image: 'https://changenow.io/images/coins/cvc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ppt',
    name: 'Populous',
    image: 'https://changenow.io/images/coins/ppt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'kan',
    name: 'BitKan',
    image: 'https://changenow.io/images/coins/kan.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'gas',
    name: 'Neo Gas',
    image: 'https://changenow.io/images/coins/gas.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'fun',
    name: 'FunFair',
    image: 'https://changenow.io/images/coins/fun.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: true,
  },
  {
    ticker: 'sys',
    name: 'Syscoin',
    image: 'https://changenow.io/images/coins/sys.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'eng',
    name: 'Enigma',
    image: 'https://changenow.io/images/coins/eng.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'grs',
    name: 'Groestlcoin',
    image: 'https://changenow.io/images/coins/grs.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'husd',
    name: 'HUSD',
    image: 'https://changenow.io/images/coins/husd.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: false,
  },
  {
    ticker: 'brd',
    name: 'Bread',
    image: 'https://changenow.io/images/coins/brd.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'poly',
    name: 'Polymath',
    image: 'https://changenow.io/images/coins/poly.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'storm',
    name: 'Storm',
    image: 'https://changenow.io/images/coins/storm.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'agi',
    name: 'SingularityNET',
    image: 'https://changenow.io/images/coins/agi.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'go',
    name: 'GoChain',
    image: 'https://changenow.io/images/coins/go.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'cnd',
    name: 'Cindicator',
    image: 'https://changenow.io/images/coins/cnd.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'mda',
    name: 'Moeda Loyalty Points',
    image: 'https://changenow.io/images/coins/mda.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'celr',
    name: 'Celer Network',
    image: 'https://changenow.io/images/coins/celr.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'wabi',
    name: 'Tael',
    image: 'https://changenow.io/images/coins/wabi.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'cmt',
    name: 'CyberMiles',
    image: 'https://changenow.io/images/coins/cmt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'pay',
    name: 'TenXPay',
    image: 'https://changenow.io/images/coins/pay.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'bqx',
    name: 'Ethos',
    image: 'https://changenow.io/images/coins/bqx.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'adx',
    name: 'AdEx',
    image: 'https://changenow.io/images/coins/adx.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'gto',
    name: 'Gifto',
    image: 'https://changenow.io/images/coins/gto.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'rdn',
    name: 'Raiden Network Token',
    image: 'https://changenow.io/images/coins/rdn.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'sngls',
    name: 'SingularDTV',
    image: 'https://changenow.io/images/coins/sngls.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'perl',
    name: 'Perlin',
    image: 'https://changenow.io/images/coins/perl.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'soc',
    name: 'All Sports',
    image: 'https://changenow.io/images/coins/soc.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'xchf',
    name: 'CryptoFranc',
    image: 'https://changenow.io/images/coins/xchf.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: true,
    supportsFixedRate: false,
  },
  {
    ticker: 'utk',
    name: 'Utrust',
    image: 'https://changenow.io/images/coins/utk.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'srn',
    name: 'SIRIN LABS Token',
    image: 'https://changenow.io/images/coins/srn.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'evx',
    name: 'Everex',
    image: 'https://changenow.io/images/coins/evx.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'blz',
    name: 'Bluzelle',
    image: 'https://changenow.io/images/coins/blz.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'dock',
    name: 'Dock',
    image: 'https://changenow.io/images/coins/dock.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'amb',
    name: 'Ambrosus',
    image: 'https://changenow.io/images/coins/amb.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'poe',
    name: 'Po.et',
    image: 'https://changenow.io/images/coins/poe.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'dlt',
    name: 'Agrello',
    image: 'https://changenow.io/images/coins/dlt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'dnt',
    name: 'district0x',
    image: 'https://changenow.io/images/coins/dnt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'snm',
    name: 'SONM',
    image: 'https://changenow.io/images/coins/snm.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'vib',
    name: 'Viberate',
    image: 'https://changenow.io/images/coins/vib.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'vibe',
    name: 'VIBE',
    image: 'https://changenow.io/images/coins/vibe.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'arn',
    name: 'Aeron',
    image: 'https://changenow.io/images/coins/arn.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ast',
    name: 'AirSwap',
    image: 'https://changenow.io/images/coins/ast.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'lxt',
    name: 'Litex',
    image: 'https://changenow.io/images/coins/lxt.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'lun',
    name: 'Lunyr',
    image: 'https://changenow.io/images/coins/lun.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'clo',
    name: 'Callisto Network',
    image: 'https://changenow.io/images/coins/clo.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ong',
    name: 'Ontology Gas',
    image: 'https://changenow.io/images/coins/ong.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'xaut',
    name: 'Tether Gold',
    image: 'https://changenow.io/images/coins/xaut.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'node',
    name: 'Whole Network',
    image: 'https://changenow.io/images/coins/node.svg',
    hasExternalId: false,
    isFiat: false,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'usd',
    name: 'Dollar',
    image: 'https://changenow.io/images/coins/usd.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'gbp',
    name: 'British Pound Sterling',
    image: 'https://changenow.io/images/coins/gbp.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'cad',
    name: 'Canadian Dollar',
    image: 'https://changenow.io/images/coins/cad.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'jpy',
    name: 'Japanese Yen',
    image: 'https://changenow.io/images/coins/jpy.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'rub',
    name: 'Russian Ruble',
    image: 'https://changenow.io/images/coins/rub.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'aud',
    name: ' Australian Dollar',
    image: 'https://changenow.io/images/coins/aud.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'chf',
    name: 'Swiss Franc',
    image: 'https://changenow.io/images/coins/chf.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'czk',
    name: 'Czech Koruna',
    image: 'https://changenow.io/images/coins/czk.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'dkk',
    name: 'Danish Krone',
    image: 'https://changenow.io/images/coins/dkk.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'nok',
    name: ' Norwegian Krone',
    image: 'https://changenow.io/images/coins/nok.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'nzd',
    name: 'New Zealand Dollar',
    image: 'https://changenow.io/images/coins/nzd.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'pln',
    name: 'Polish Złoty',
    image: 'https://changenow.io/images/coins/pln.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'sek',
    name: 'Swedish Krona',
    image: 'https://changenow.io/images/coins/sek.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'try',
    name: 'Turkish Lira',
    image: 'https://changenow.io/images/coins/try.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'zar',
    name: 'South African Rand',
    image: 'https://changenow.io/images/coins/zar.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'huf',
    name: 'Hungarian Forint',
    image: 'https://changenow.io/images/coins/huf.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'ils',
    name: 'Israeli New Shekel',
    image: 'https://changenow.io/images/coins/ils.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
  {
    ticker: 'krw',
    name: 'South Korean Won',
    image: 'https://changenow.io/images/coins/krw.svg',
    hasExternalId: false,
    isFiat: true,
    featured: false,
    isStable: false,
    supportsFixedRate: false,
  },
];
